### ISSUE TITLE
Adopt commitlint standards

### ISSUE THREAD

**Issue by jamesgeorge007** [madlabsinc/mevn-cli#139]
We're gonna follow commitlint standards while framing up the commit messages.
Refer these [guidelines](https://commitlint.js.org/#/guides-local-setup).

- [ ] install `commitlint-cli` as a `dev-dependency`.
- [ ] configure `pre-commit`  hook with `husky`.
- [ ] update docs to include a dedicated section regarding how to write commit messages based on the standards.

**Comment by klauskpm** [comment]
I would like to work on this.

**Comment by jamesgeorge007** [comment]
@klauskpm sure, feel free to shoot up a PR :+1:

**Comment by jamesgeorge007** [comment]
Done in #140
