### ISSUE TITLE
Upgrade execa

### ISSUE THREAD

**Issue by abhijithvijayan** [madlabsinc/mevn-cli#142]
The package `execa` has so many updates and deprecated options.

Shouldn't this be updated?

**Comment by jamesgeorge007** [comment]
Feel free to shoot a PR :clap:

**Comment by jamesgeorge007** [comment]
It seems this is gonna introduce breaking changes due to the API changes.

**Comment by abhijithvijayan** [comment]
But first, if a list of commands used could be sorted and listed, that would be easier for as to check if deprecated or not

**Comment by abhijithvijayan** [comment]
execa.syncShell is to be replaced with

execa(command, {shell: true})

**Comment by abhijithvijayan** [comment]
Is this ready to be worked on?

**Comment by abhijithvijayan** [comment]
Feel free to assign this to somebody else.

I may not get time to get back to this.

**Comment by jamesgeorge007** [comment]
Not of higher priorities.
