### ISSUE TITLE
[chore]: deploy command is buggy

### ISSUE THREAD

**Issue by AlMuz** [madlabsinc/mevn-cli#151]
**Describe the bug**
Hello. 
I tried to deploy project using `mevn deploy`(using git) but it always return this error:

> remote:  !     No default language could be detected for this app.
> remote: 			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
> remote: 			See https://devcenter.heroku.com/articles/buildpacks
> remote: 
> remote:  !     Push failed

After that, when i tried to execute this command again its create another one heroku app instead of using existing one.

Maybe there is possible to detect connected git remote url and if it exists - dont create new app.

Also there must be more information for deployment section( need to create it first).

Also when i tried to deploy with docker it returns.
 >  No images to push

So if it possible. Can you provide more information, how to deploy.
**To Reproduce**

1.Download this project https://github.com/AlMuz/VUE-AlmuzWebsite
1. `mevn deploy`
1. Deploy with Git
1. Confirm heroku auth on website
1. **ERROR**

**Expected behavior**
I expected what it will be deployed on heroku. That's all.

**Environment Info**
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz
  Binaries:
    Node: 9.6.1 - /usr/local/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
  npmGlobalPackages:
    mevn-cli: 1.6.1

**Comment by jamesgeorge007** [comment]
@AlMuz thank you for raising the issue. Deployment to Heroku platform seems to be buggy. Wanna shoot a PR for this? Meanwhile if you are just having a SPA go with `surge`.

**Comment by aquibbaig** [comment]
@AlMuz Thanks for raising this issue. Mind if I work on this?

**Comment by AlMuz** [comment]
@aquibbaig Hello. Go on. Because i dont really know how to fix it..

**Comment by jamesgeorge007** [comment]
Fixed in [v1.7.0](https://github.com/madlabsinc/mevn-cli/releases/tag/v1.7.0)
