### ISSUE TITLE
Migrate to enquirer

### ISSUE THREAD

**Issue by jamesgeorge007** [madlabsinc/mevn-cli#156]
## Present Scenario
We're currently using [inquirer.js](https://github.com/SBoudrias/Inquirer.js/) for the interactive prompts. This has led to a huge rise in the bundle size as inquirer depends on a couple of packages.

## Proposed Solution
 Switch to [enquirer](https://github.com/enquirer/enquirer).

**Comment by aquibbaig** [comment]
Hey @jamesgeorge007. Can I work on this one here? Cause it will make me catch up with the work till now!

**Comment by jamesgeorge007** [comment]
@aquibbaig yeah ofc :clap:

**Comment by jamesgeorge007** [comment]
[enquirer](https://github.com/enquirer/enquirer) would be a better choice as it has got a similar API.

**Comment by jamesgeorge007** [comment]
Not of higher priorities.
