### ISSUE TITLE
Open client service in the browser with correct port after vue-cli-service starts

### ISSUE THREAD

**Issue by pksjce** [madlabsinc/mevn-cli#164]
**Describe the bug**
After creating a basic project, I tried to serve the client and the browser opened up at the wrong port

**To Reproduce**
mevn init // create a new project
mevn serve // shows options client/server
choose client
Opens up the browser with port 8080 and it is blank.
The actual app had launched at a different port.

**Expected behavior**
It must open up in the port sent by `launch.js` and open in browser after the service starts

**Environment Info**
node v12.15.0
Mac env

**Comment by jamesgeorge007** [comment]
Fixed in `v1.7.0`
