### ISSUE TITLE
Unhandled Warning 

### ISSUE THREAD

**Issue by alanmathew333** [MadlabsInc/mevn-cli#17]
Repeated execution of server commands like:-
 
mevn-cli create:controller
mevn-cli create:route
...
will create the file but the repeated execution of these commands will note prompt warnings like 
"The file already exist and do you wish to create anyway" and receiving user input as yes/no.

**Comment by darrylpargeter** [comment]
Hey, would it be possible to tackle this one?

**Comment by jamesgeorge007** [comment]
I shall supply more details about the bug since one can't infer from what is already provided :+1:

**Comment by jamesgeorge007** [comment]
> The tool comes up with options to automate the creation of files within model, controller and route directories as well as config which is takes in the DB url. 

This is made possible with mevn-cli create:<required_option> which will create the respective file for the very first time.
Firing in the command again is not handled properly. What was intended is to warn the users with a suitable message, such as the file was already created or similar.

Check out the below screenshot:

![screenshot from 2018-10-04 19-21-59](https://user-images.githubusercontent.com/25279263/46478568-e6ab1500-c80a-11e8-964f-a5ce6bbda64f.png)

**Comment by darrylpargeter** [comment]
So would you want it to warn and get permission to overwrite the file as mentioned in the first comment or to kill the process so the user dosen't accidentally overwrite the file with a message explaining why it wasn't created?

**Comment by alanmathew333** [comment]
To warn and get permission to overwrite the file, if answer provided by the user is yes and to kill the process if the answer is NO

**Comment by alanmathew333** [comment]
@darrylpargeter great job :+1:
