### ISSUE TITLE
Set up MongoDB configurations automatically with mevn generate

### ISSUE THREAD

**Issue by jamesgeorge007** [madlabsinc/mevn-cli#176]
`mevn generate` aims to provide a CRUD boilerplate template so the users can work on top of it.
https://github.com/madlabsinc/mevn-cli/blob/6688a3d25a658f01ff302302cf850b9976de6529/src/templates/server/basic/server.js#L5
https://github.com/madlabsinc/mevn-cli/blob/6688a3d25a658f01ff302302cf850b9976de6529/src/templates/server/basic/server.js#L27-L36

Have a helper with the necessary configuration as given above and import it within `server.js`.

**Comment by danivijay** [comment]
@jamesgeorge007 I'll try implementing this.
