### ISSUE TITLE
mevn deploy to heroku issues

### ISSUE THREAD

**Issue by avdrav** [madlabsinc/mevn-cli#177]
**Describe the bug**
I'm attempting to deploy a fairly fresh set of changes to heroku.  However, after I make the change, I get the message --> NO CHANGES DETECTED.  I am definitely making changes and git is detecting them.  But for some reason, the deploy script won't detect them.

**To Reproduce**
Using this public repo for now --> https://github.com/avdrav/imfcharts

**Expected behavior**
Expected change to appear in heroku

**Screenshots**

**Environment Info**
  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
  Browsers:
    Firefox: 78.0.1
  npmGlobalPackages:
    mevn-cli: 1.7.5

**Additional context**

**Comment by jamesgeorge007** [comment]
I assume things went well when you ran `mevn deploy` for the very first time. Can you please elaborate the changes you made prior to firing in `mevn deploy` for the second time?
I did gave it a try on your repo and things were working fine.

**Comment by avdrav** [comment]
correct it happens on the second try.  it worked great on the initial push.

i made some very simple changes adding a connector to a mongodb atlas instance.  i also made a call to the reddit api.  thats it.

**Comment by avdrav** [comment]
https://github.com/avdrav/imfcharts/commits/master

**Comment by jamesgeorge007** [comment]
That's strange. Can you please give it a try on the `beta` release and confirm if things remain the same - `mevn-cli@beta`

**Comment by avdrav** [comment]
whats the cleanest way to switch to the beta?  uninstall and re-install using npm?

**Comment by avdrav** [comment]
ok tried that.  upgraded to v1.7.5 of mevn-cli and still getting the same error.  No changes detected

**Comment by avdrav** [comment]
hmm looks like i was already on the beta?

**Comment by avdrav** [comment]
are you able to reproduce on your end after making a simple change to the codebase?

**Comment by jamesgeorge007** [comment]
> whats the cleanest way to switch to the beta?  uninstall and re-install using npm?

`npm i -g mevn-cli@beta`

**Comment by jamesgeorge007** [comment]
> are you able to reproduce on your end after making a simple change to the codebase?

Nope, I made a slight change to one of the components firing in `mevn deploy` did the job.

**Comment by jamesgeorge007** [comment]
> https://github.com/avdrav/imfcharts/commits/master

Your latest commit targets the `server` directory. As of `v1.7.5` there isn't the provision to deploy the `server`. It is just the `client` directory which is being watched.

**Comment by avdrav** [comment]
so how to deploy the server piece now?

**Comment by avdrav** [comment]
yes it works when i touch the client.  but im confused as to how to deploy the server/api piece now.  my assumption was that mevn deploy does both.  bad assumption?

**Comment by avdrav** [comment]
thanks for all your help btw!

**Comment by jamesgeorge007** [comment]
> yes it works when i touch the client.  but im confused as to how to deploy the server/api piece now.  my assumption was that mevn deploy does both.  bad assumption?

As I said `v1.7.5` doesn't include the provision to deploy the server. It is gonna come up with the next minor release: `v1.8.0` which is in `beta` right now.

**Comment by jamesgeorge007** [comment]
@avdrav if you feel your issue has been resolved, feel free to close this issue :)
And if you're liking the project don't forget to leave a ⭐
Looking forward to having your very first contribution to the project 🙌

**Comment by avdrav** [comment]
Awesome -- will the beta version create Procfile?  How will it run the server on Heroku?

**Comment by jamesgeorge007** [comment]
Nope, both of em are deployed as seperate apps to Heroku.

**Comment by jamesgeorge007** [comment]
I'm gonna close it for now. Feel free to shoot your queries here :)

**Comment by avdrav** [comment]
So i tried to deploy the server using 1.8.0-beta.5
Here is the error I get.  I works locally.

`2020-07-06T17:15:43.539338+00:00 app[web.1]: SyntaxError: Cannot use import statement outside a module
2020-07-06T17:15:43.539339+00:00 app[web.1]: at wrapSafe (internal/modules/cjs/loader.js:1054:16)
2020-07-06T17:15:43.539339+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:1102:27)
2020-07-06T17:15:43.539359+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2020-07-06T17:15:43.539360+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:986:32)
2020-07-06T17:15:43.539360+00:00 app[web.1]: at Function.Module._load (internal/modules/cjs/loader.js:879:14)
2020-07-06T17:15:43.539371+00:00 app[web.1]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
2020-07-06T17:15:43.539371+00:00 app[web.1]: at internal/main/run_main_module.js:17:47
2020-07-06T17:15:43.550207+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-07-06T17:15:43.550591+00:00 app[web.1]: npm ERR! errno 1
2020-07-06T17:15:43.552157+00:00 app[web.1]: npm ERR! server@1.0.0 start: `node server.js`
2020-07-06T17:15:43.552352+00:00 app[web.1]: npm ERR! Exit status 1
2020-07-06T17:15:43.552582+00:00 app[web.1]: npm ERR!
2020-07-06T17:15:43.552758+00:00 app[web.1]: npm ERR! Failed at the server@1.0.0 start script.
2020-07-06T17:15:43.552920+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by avdrav** [comment]
@jamesgeorge007 any thoughts on this?  still stuck at this error when I try the heroku server deploy

**Comment by jamesgeorge007** [comment]
Apologies for the delay in response. I can see that your codebase consumes `ES6` syntax (`import` statements).
https://github.com/avdrav/imfcharts/blob/437257b03d99e5d20db15bab97613e0e3c0b4c35/server/server.js#L2
```js
const express = require('express')
```
You can get it working by converting them to the `es5` equivalent. Or if you prefer to have modern syntax, make use of a transpiler like `babel` or something like [esm](https://github.com/standard-things/esm).

**Comment by jamesgeorge007** [comment]
@avdrav I had sent you a connection request in LinkedIn, let's connect 👍

**Comment by avdrav** [comment]
But shouldn't the build/deploy process take this into account?  I haven't written any custom code yet -- just trying to deploy the Hello World example basically.

**Comment by avdrav** [comment]
@jamesgeorge007

**Comment by avdrav** [comment]
Also why does it work locally but not on the deploy?

**Comment by jamesgeorge007** [comment]
The latest release (v1.7.5) seems to be using `ES6` syntax for the server side template.
