### ISSUE TITLE
feat: Default model enhancements and API error handling

### ISSUE THREAD

**Issue by danivijay** [madlabsinc/mevn-cli#180]
**Is your feature request related to a problem? Please describe.**
The default scaffolded model a bit limited, and there is some room for improvement in the error handling part of the API.

**Describe the solution you'd like**
Changes in Model
- Auto-generated ID
- Timestamps

Changes in Controller
- JSON response for queries
- Error handling

**Describe alternatives you've considered**
Considered adding an auth template, but seems like it'll be better to tackle that alone as an independent feature if needed.

**Comment by jamesgeorge007** [comment]
Feel free to shoot a PR 👍
