### ISSUE TITLE
mevn init fails on PWA template

### ISSUE THREAD

**Issue by nerrevar** [MadlabsInc/mevn-cli#196]
**Describe the bug**
mevn init requires PWA folder for creating from template. There is pwa folder.

**To Reproduce**
mevn init -> choose PWA

**Additional context**
Just rename folder pwa -> PWA. After that mevn works good.

**Comment by open-source-explorer** [comment]
@nerrevar can you provide more details, possibly a screenshot? Also, are you on a windows machine?
