### ISSUE TITLE
bump commander.js to v6

### ISSUE THREAD

**Issue by jamesgeorge007** [MadlabsInc/mevn-cli#207]
Currently, the project depends on [commander.js v2](https://www.npmjs.com/package/commander/v/2.20.3) while we have [v6](https://www.npmjs.com/package/commander/v/6.2.0) as the latest stable release. We can safely bump the package.

**Comment by jamesgeorge007** [comment]
```bash
npm install commander@latest
```

https://github.com/madlabsinc/mevn-cli/blob/develop/src/cli.js

```diff
@@ -89,9 +89,11 @@ program
       .then(console.log);
   });

-program.arguments('<command>').action((cmd) => {
+// Validation for unknown commands
+program.on('command:*', ([cmd]) => {
   program.outputHelp();
-  console.log(`  ` + chalk.red(`\n  Unknown command ${chalk.yellow(cmd)}.`));
+  console.log();
+  console.error(` Unknown command ${chalk.yellow(cmd)}.`);
   console.log();
   suggestCommands(cmd);
 });
```

**Comment by Creatoon** [comment]
@jamesgeorge007 Can you please elaborate the issue, I want to work on this.

**Comment by Creatoon** [comment]
working on this
