### ISSUE TITLE
Add SSR option with Nuxt.js

### ISSUE THREAD

**Issue by jamesgeorge007** [madlabsinc/mevn-cli#26]
Currently the user is welcomed with 3 options (Boilerplate):
- Basic
- PWA
- GraphQL

> As a fourth option provide support SSR capability with `Nuxt-js`

Further he/she should be prompted to go with either `Universal` / `SPA`

**Comment by Apoorva-13** [comment]
Hi i would like to work on this?? But can u help me get started with this. I am new to Node

**Comment by jamesgeorge007** [comment]
@Apoorva-13 Check out [Node school](https://nodeschool.io)
