### ISSUE TITLE
Implement GraphQL

### ISSUE THREAD

**Issue by jamesgeorge007** [MadlabsInc/mevn-cli#28]
For now the server part supports only traditional RESTful API which has to be extended with GraphQL.

**Comment by ajomadlabs** [comment]
@JoshDev1205 Sure go on. Yeah we can go with creating boilerplate for both server and client that supports graphql

**Comment by jamesgeorge007** [comment]
@JoshDev1205 For the boilerplate part there is already a basic boilerplate available 
[here(https://github.com/MadlabsInc/mevn-boilerplate). You may clone this repository and add the additional dependencies required within the ```client``` and ```server``` part.
