### ISSUE TITLE
Implement passport auth middleware

### ISSUE THREAD

**Issue by jamesgeorge007** [MadlabsInc/mevn-cli#44]
Ask the user whether he requires passport middleware for authentication and install the required dependencies.

**Comment by konsvasi** [comment]
At what point in the app will this question be asked to the user? If the answer is yes do you just want to do an `npm install` of the package? It's similar to the other issues that I've worked on and I believe that I can solve it.

**Comment by jamesgeorge007** [comment]
Thank you once again for showing interest :+1: Yup, it involves installing the required package as in the earlier cases. It would be great if you could populate the routes file with say a ```login``` end-point having  authentication implemented by passport middleware. 
Additionally the user should also be asked whether he require social media authentication that comes as part of passport.

**Comment by konsvasi** [comment]
Okay, I'll take a look at it

**Comment by konsvasi** [comment]
Can you check my [commit](https://github.com/konsvasi/mevn-cli/commit/d1a2d7dcf00c447579a1261a97b9296a379a9c56) and tell me if it is okay, especially the new `index_with_passport.js` file. Is this how you had it in mind? If it's okay than I'll go on with the social media authentication.

**Comment by jamesgeorge007** [comment]
LGTM Go ahead :+1:
