### ISSUE TITLE
Add axios dependency

### ISSUE THREAD

**Issue by jamesgeorge007** [MadlabsInc/mevn-cli#45]
Ask the user whether he requires axios to link up the client and server part. If so, add the required dependencies and couple of boilerplate code.

**Comment by virenb** [comment]
I added axios package to dependencies in the package.json file.

**Comment by ajomadlabs** [comment]
@virenb Great to see your interest :smile: Currently you have just added the axios package but according to the requirements we need to have 
- command `mevn-cli add:package <package_name>`
- On entering this command, we need to list the packages we support. At present just show axios.
- User on selecting axios, we need to install that package in the package.json file of the boilerplate code thats already been downloaded

Do comment if you have any further queries
