### ISSUE TITLE
Provide support for webpack 4 

### ISSUE THREAD

**Issue by jamesgeorge007** [madlabsinc/mevn-cli#50]
Migration from `webpack v3` to `v4` requires a lot of manual configurations which has to be automated with a particular command.

**Comment by jamesgeorge007** [comment]
@hansika Are you working on this?

**Comment by codehansika** [comment]
I m willing to work on this issue

**Comment by anto-christo** [comment]
@codehansika, go ahead 👍

**Comment by jamesgeorge007** [comment]
@codehansika Any updates :thinking:

**Comment by abhijithvijayan** [comment]
where exactly is the upgrade needed?

**Comment by jamesgeorge007** [comment]
@abhijithvijayan Thank you showing interest :clap: As per now all the boilerplate templates are based on webpack `v3`. What intended is a dedicated command such as `mevn configure` with an entry for `v4` migration. Check out these [guidelines](https://webpack.js.org/migrate/4/)

**Comment by abhijithvijayan** [comment]
It is a long path, but I guess I could look at it during free time.

**Comment by jamesgeorge007** [comment]
Feel free to reach out :+1:

**Comment by jamesgeorge007** [comment]
As per `v1.6` release, the boilerplate templates use webpack v4 under the hoods.
