### ISSUE TITLE
mevn-cli website homepage

### ISSUE THREAD

**Issue by jamesgeorge007** [MadlabsInc/mevn-cli#52]
As per now what we have is just the documentation part done in vuepress. We require a homepage that will serve the purpose of an intro section having a brief description of the tool.

For this you are required to work with the  ```README.md``` file within ```docs``` directory.

**Comment by jamesjose03** [comment]
Working on it 😄 @jamesgeorge007

**Comment by jamesgeorge007** [comment]
:+1:

**Comment by ajomadlabs** [comment]
Issue Fixed
