### ISSUE TITLE
Warn the user if docker is not installed 

### ISSUE THREAD

**Issue by jamesgeorge007** [madlabsinc/mevn-cli#71]
## Present scenario

Currently, `mevn dockerize` expects to have access to `docker-compose` within the machine. It crashes yelling that `docker-compose` not found which is a default message as thrown by the system.

## What is to be done

Handle the failing case such that a custom message is shown instead. Also, there should be a prompt asking the user if he/she should get it installed (Y/N) and go forward with the installation.

> Linux/Mac

**Comment by aquibbaig** [comment]
I want to work on this!

**Comment by anto-christo** [comment]
Fixed in #92
