### ISSUE TITLE
Warn the user if git is not installed

### ISSUE THREAD

**Issue by jamesgeorge007** [madlabsinc/mevn-cli#72]
## Present scenario

Currently, `mevn create:git-repo` expects to have access to `git` within the machine. A default error message is thrown.

## What is to be done

Handle the failing case such that a custom message is shown instead. Also, there should be a prompt asking the user if he/she should get it installed (Y/N) and go forward with the installation.

> Linux/Mac

**Comment by aquibbaig** [comment]
I would like to work on this @jamesgeorge007

**Comment by jamesgeorge007** [comment]
@aquibbaig Sure, go ahead :+1:

**Comment by jamesgeorge007** [comment]
Fixed in #75
