### ISSUE TITLE
Add provision to have pwa support for Nuxt-js template

### ISSUE THREAD

**Issue by jamesgeorge007** [madlabsinc/mevn-cli#74]
Currently, the user can only have the basic template if he chooses `Nuxt-js` from the list.
It should be made such that the user will be prompted whether he/she requires `pwa` support after making the selection as mentioned above. 
See these [guidelines](https://pwa.nuxtjs.org/setup.html)

**Comment by aquibbaig** [comment]
I can try this issue!

**Comment by anto-christo** [comment]
@aquibbaig sure, go ahead 👍
