### ISSUE TITLE
Separate the sections of Docs

### ISSUE THREAD

**Issue by jamesjose03** [madlabsinc/mevn-cli#78]
Separate each section of the docs into individual pages and render them only when clicked.
Here's the file to work with:  [README.md](https://github.com/madlabsinc/mevn-cli/tree/master/docs/guide)

**Comment by agarwalrounak** [comment]
I will work on this issue.

**Comment by ajomadlabs** [comment]
@agarwalrounak Sure :+1:

**Comment by ajomadlabs** [comment]
@agarwalrounak Feel free to ask your queries :smile:

**Comment by agarwalrounak** [comment]
I will work on this issue now.

**Comment by agarwalrounak** [comment]
@ajomadlabs @jamesgeorge007 Can you please let me know what exactly is to be done? I am sorry but I can't seem to clearly understand the issue.

**Comment by ajomadlabs** [comment]
@agarwalrounak Sorry for the delayed response, so right now the documentation is done using vuepress. Vuepress is basically a static site generator made with vue. You could checkout more on vuepress [here](https://vuepress.vuejs.org/).

Present scenario we have written the enitre documentation in one single mardown file. So we would like you to separate the documentation into separate markdown files.

**Comment by agarwalrounak** [comment]
Is the documentation deployed/online somewhere?

**Comment by ajomadlabs** [comment]
@agarwalrounak Yes, you could check [this](https://mevn.madhacks.co/)

**Comment by aquibbaig** [comment]
I don't think there is much progress here, I will gladly take this issue up

**Comment by jamesgeorge007** [comment]
@aquibbaig Go ahead :+1:
