### ISSUE TITLE
Update all instances of mevn within the list of commands

### ISSUE THREAD

**Issue by jamesgeorge007** [madlabsinc/mevn-cli#79]
### Present issue

On firing in `mevn init <webapp>` the user is presented with a list of available commands where it shows up `mevn-cli` instead of `mevn`

### Proposed solution

Update all the instances of `mevn-cli` with `mevn`

This is the file to work with: [initlib](https://github.com/madlabsinc/mevn-cli/blob/master/lib/commands/initlib.js)

**Comment by kamerk22** [comment]
I 've submitted to fix above issue. Sorry that I forgot to discuss it before opening PR.

**Comment by ajomadlabs** [comment]
Fixed #83
