### ISSUE TITLE
Update File Hierarchy within docs

### ISSUE THREAD

**Issue by jamesjose03** [madlabsinc/mevn-cli#80]
Update the file hierarchy in docs according to the latest changes. 
Here's the file to work with: [File Hierarchy Section](https://github.com/madlabsinc/mevn-cli/tree/master/docs/guide#file-hierarchy)

**Comment by kamerk22** [comment]
@jamesjose03 I can help

**Comment by jamesjose03** [comment]
@kamerk22 Sure, just go ahead.👍👍

**Comment by kamerk22** [comment]
@jamesjose03 Do I need to update hierarchy with all the file in the repository? The current section having only the structure of `lib` dir and other files. [Checkout Updated One](https://github.com/kamerk22/mevn-cli/tree/master/docs/guide#file-hierarchy)

**Comment by jamesjose03** [comment]
@kamerk22 Yes, Hierarchy is to be updated with all the files.

**Comment by ajomadlabs** [comment]
Fixed #84

**Comment by agarwalrounak** [comment]
I will work on this issue.

**Comment by ajomadlabs** [comment]
@agarwalrounak you could take this up :+1:

**Comment by jamesgeorge007** [comment]
There have been couple of changes to the project structure as on release `v1.2.0`
