### ISSUE TITLE
[Question] Placement of mevn.json file

### ISSUE THREAD

**Issue by anto-christo** [madlabsinc/mevn-cli#86]
Hi,
I have some doubts regarding the mevn.json file.

If I'm not wrong, the mevn.json file contains info regarding a particular project. Then why is it outside of the project directory, shouldn't it be inside the project directory since it is specific to it?

Due to the placement of mevn.json file outside the project directory, the user cannot create more than one project in the same location. Also, due to this, the user currently has to execute project-specific commands (like create: component, etc) outside of the project directory, ideally those commands should be called within the specific projects.

May I know the reason and thought process behind the placement of mevn.json file? 
Thank you.

**Comment by jamesgeorge007** [comment]
You're right :+1: 
You can see an update soon

**Comment by jamesgeorge007** [comment]
You're right :+1: There'll be an update soon

**Comment by ajomadlabs** [comment]
Fixes #87
