### ISSUE TITLE
Avoid the callback hell and use promises instead

### ISSUE THREAD

**Issue by jamesgeorge007** [madlabsinc/mevn-cli#90]
Currently [gitRepo.js](https://github.com/madlabsinc/mevn-cli/blob/master/lib/commands/deploy/gitRepo.js) comprises of nested callbacks making the code ambiguous. It has to be replaced with a promisified approach.
> Use async/await and promises 

Check out [herokuDeployjs](https://github.com/madlabsinc/mevn-cli/blob/master/lib/commands/deploy/herokuDeploy.js)

**Comment by mansim3006** [comment]
can I work on this issue?

**Comment by anto-christo** [comment]
Sure, go ahead 👍

**Comment by ani-sha** [comment]
Can I work on this issue?

**Comment by anto-christo** [comment]
Hi @ani-sha , glad to see you interested in this issue. But this has already been assigned to another participant. The other participant is hopefully working on it and may send a PR. We can assign you this if the previous participant fails to do so. Till then I request you to have a look at other issues. I recommend you #81 . The participant assigned to #81 has not been responsive, so if you are interested, we can assign #81 to you.

**Comment by ani-sha** [comment]
@anto-christo Sorry for the late reply I was out of station. 
Yes i would like to work on #81 issue. Please assign me.
