### ISSUE TITLE
Update commands section within docs

### ISSUE THREAD

**Issue by jamesgeorge007** [madlabsinc/mevn-cli#95]
- Remove `Server Commands` section.
- Rename `General Commands` to `Available Commands`.
- Add missing entries within the list of `Available Commands`.
- Change `mevn run client/server` to `mevn serve`

This is the file to work with: [README](https://github.com/madlabsinc/mevn-cli/blob/master/docs/guide/README.md)
> Refer [Repo Readme](https://github.com/madlabsinc/mevn-cli/blob/master/README.md)

**Comment by souka1** [comment]
I would like to work on it

**Comment by jamesgeorge007** [comment]
@souka1 Sure, Go ahead :clap:

**Comment by jamesgeorge007** [comment]
Done in #99
